### ISSUE TITLE
Error using worker-loader plugin

### ISSUE THREAD

**Issue by davidfraser** [istarkov/babel-plugin-webpack-loaders#136]
I'm using the [worker-loader](https://www.npmjs.com/package/worker-loader) plugin, which uses the exclamation-based loader syntax in imports:

```javascript
import worker from "worker!./hash.js"
```

This doesn't work:
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'worker!hash.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (run.js:3:1)
    at Module._compile (module.js:409:26)
    at loader (/tmp/babel-plugin-webpack-loaders/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/babel-plugin-webpack-loaders/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Is there any way to support this functionality?

**Comment by istarkov** [comment]
As I know `webworkers` are not available on server side, so there is no need to build them on the server. 
And as current plugin [intended](https://github.com/istarkov/babel-plugin-webpack-loaders#warning) for server builds only, so no support will come.
Also even there are some polyfills available, the problem that in most cases just replacing require with module exports is not enough (have you seen webpack modules boilerplate). 

So sorry ;-) I can't do much here.

**Comment by davidfraser** [comment]
OK that makes sense. I am trying to run portions of our application serverside, and the imports cause problems because they are hard to do conditionally. So I will just have to find a workaround to that. Thanks for the quick feedback

**Comment by davidfraser** [comment]
For future reference for anyone else browser on this, the following solved this:
```javascript
// We can't import webworker when running from node, and since imports are static, we need to require it dynamically
const IN_BROWSER = (typeof document != 'undefined')
let hashWorker = null
if (IN_BROWSER) {
  hashWorker = require("worker!../workers/hash.js")
}
```
