### ISSUE TITLE
v0.3.0 Issue

### ISSUE THREAD

**Issue by oliviertassinari** [istarkov/babel-plugin-webpack-loaders#24]
I have tried to upgrade to v0.3.0 however that's no longer working.
My source code looks like (`src/Main/Product.jsx`):
```js
...

import polyglot from 'polyglot'; // Located in src/polyglot.js

// import imageIcon from 'Main/Product/icon.png'; (I can't make it work)
import imageIcon from './icon.png';

....
```

Here is the stack trace:
```
/Users/oliviertassinari/SplitMe/node_modules/babel-core/lib/transformation/file/index.js:585
      throw err;
      ^

Error: /Users/oliviertassinari/SplitMe/src/Main/Product/Footer.jsx: Can't resolve 'polyglot' in '/Users/oliviertassinari/SplitMe/src/Main/Product'
    at onResolved (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:64:16)
    at loggingCallbackWrapper (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:136:10)
    at loggingCallbackWrapper (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Tapable.applyPluginsAsyncSeriesBailResult1 (/Users/oliviertassinari/SplitMe/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:123:19)
    at loggingCallbackWrapper (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/oliviertassinari/SplitMe/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:121:11)
    at loggingCallbackWrapper (/Users/oliviertassinari/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
```

**Comment by istarkov** [comment]
Hi, as you understand this is an opensource project, and the main purpose of this project is to work for me and for my projects, 
so please provide broken tests here .
 I really have no ability to download and check every project with errors.

I can get nothing from your stack trace, all I can see that library I have never seen before can't be found.

**Comment by oliviertassinari** [comment]
> Hi, as you understand this is an opensource project, and the main purpose of this project is to work for me and for my projects, 

That makes sense :+1:. I will try to submit a PR to fix this.

**Comment by istarkov** [comment]
:-)

**Comment by istarkov** [comment]
May be this helps https://github.com/istarkov/babel-plugin-webpack-loaders/pull/25

**Comment by karlhorky** [comment]
@oliviertassinari did #25 help? Can this be closed?

**Comment by oliviertassinari** [comment]
@karlhorky Unfortunately not and I hadn't had time to looke at it.
That seems to be the same issue as https://github.com/istarkov/babel-plugin-webpack-loaders/issues/4.
I'm making all my import relative to the `/src` folder of my project so that I can refactor more easily my code base. Here, `require('polyglot')` should import `src/ploglot.js`.

**Comment by karlhorky** [comment]
Did you configure the `resolve.modules` array in your webpack config?

```js
module.exports = {

// ...

  resolve: {
    modules: [
      path.resolve(__dirname),
      path.resolve(__dirname, 'src')
    ]
  },

// ...

}
```

**Comment by oliviertassinari** [comment]
@karlhorky Thanks.
Problem solved with:
```js
  resolve: {
    modules: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, 'src'),
    ],
  }, 
```
By the way, I'm using this config for my browser config.
```js
    resolve: {
      root: path.join(__dirname, 'src'),
    },
```
