### ISSUE TITLE
ModuleNotFoundError: Cannot resolve module 'fs' on versions above 0.2.3

### ISSUE THREAD

**Issue by nkbt** [istarkov/babel-plugin-webpack-loaders#28]
After the last updates:

```
✘-127 ~/nkbt/react-component-template [eslint2 L|✔] 
16:50 $ NODE_ENV=test `npm bin`/babel-node test
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'fs' in /Users/nkbt/nkbt/react-component-template/node_modules/glob
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:726:13
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:52:16
    at done (/Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:241:17)
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:44:16
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:723:17
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:167:37
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:31:26)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:28:12
    at Storage.finished (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:83:15)
resolve module fs in /Users/nkbt/nkbt/react-component-template/node_modules/glob
  looking for modules in /Users/nkbt/nkbt/react-component-template/node_modules
    /Users/nkbt/nkbt/react-component-template/node_modules/fs doesn't exist (module as directory)
    resolve 'file' fs in /Users/nkbt/nkbt/react-component-template/node_modules
      resolve file
        /Users/nkbt/nkbt/react-component-template/node_modules/fs doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.webpack.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.web.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.json doesn't exist
/Users/nkbt/nkbt/react-component-template/node_modules/babel-core/lib/transformation/file/index.js:585
      throw err;
      ^

Error: /Users/nkbt/nkbt/react-component-template/test/index.js: Command failed: node /Users/nkbt/nkbt/react-component-template/node_modules/webpack/bin/webpack.js /Users/nkbt/nkbt/react-component-template/node_modules/glob/glob.js /var/folders/tj/yys527ld7wdbf9lfh244hk_h0000gn/T/.webpack.res.1455601819228_528818.js --config ./webpack.config.js --colors --bail
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'fs' in /Users/nkbt/nkbt/react-component-template/node_modules/glob
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:726:13
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:52:16
    at done (/Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:241:17)
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:44:16
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:723:17
    at /Users/nkbt/nkbt/react-component-template/node_modules/async/lib/async.js:167:37
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:31:26)
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:28:12
    at Storage.finished (/Users/nkbt/nkbt/react-component-template/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:83:15)
resolve module fs in /Users/nkbt/nkbt/react-component-template/node_modules/glob
  looking for modules in /Users/nkbt/nkbt/react-component-template/node_modules
    /Users/nkbt/nkbt/react-component-template/node_modules/fs doesn't exist (module as directory)
    resolve 'file' fs in /Users/nkbt/nkbt/react-component-template/node_modules
      resolve file
        /Users/nkbt/nkbt/react-component-template/node_modules/fs doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.webpack.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.web.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.js doesn't exist
        /Users/nkbt/nkbt/react-component-template/node_modules/fs.json doesn't exist

    at checkExecSyncError (child_process.js:465:13)
    at execSync (child_process.js:505:13)
    at exports.default (/Users/nkbt/nkbt/react-component-template/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:41:51)
    at PluginPass.CallExpression (/Users/nkbt/nkbt/react-component-template/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:76:60)
    at newFn (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitMultiple (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/nkbt/nkbt/react-component-template/node_modules/babel-traverse/lib/context.js:198:19)
✘-1 ~/nkbt/react-component-template [eslint2 L|✔] 
```

Disabling `babel-plugin-webpack-loaders` (and css import) make tests running again.

Stepping down to `0.2.3` fixes the problem too.

```
16:54 $ npm install babel-plugin-webpack-loaders@0.2.3
react-component-template@1.0.0 /Users/nkbt/nkbt/react-component-template
├── babel-plugin-webpack-loaders@0.2.3  extraneous
└── UNMET PEER DEPENDENCY eslint@2.1.0

✔ ~/nkbt/react-component-template [eslint2 L|✔] 
16:55 $ NODE_ENV=test `npm bin`/babel-node test
TAP version 13
# Component
ok 1 should be function
# App
ok 2 should be function

1..2
# tests 2
# pass  2

# ok

✔ ~/nkbt/react-component-template [eslint2 L|✔] 
```

**Comment by istarkov** [comment]
Does problem exists on 0.3.3 version? I have test for this bug and thought this was resolved

**Comment by istarkov** [comment]
I found your problem, you need to remove this in loader section {test: /\.js$/, loader: 'babel', include: [path.resolve('src')]}

And tests begin work 'ok'

This plugin does not support js loader. 

I think I will add warning about.

**Comment by istarkov** [comment]
Done at #31
js jsx loaders are skipped
warning showed

**Comment by istarkov** [comment]
0.3.5 at npm

**Comment by nkbt** [comment]
Thanks a lot! That was really quick! https://github.com/nkbt/react-component-template/pull/66 PASS

**Comment by istarkov** [comment]
Wow what a cool thing http://greenkeeper.io/ by your ref.
Thank you!

**Comment by nkbt** [comment]
:+1:
