### ISSUE TITLE
TypeError: ..... invalid data

### ISSUE THREAD

**Issue by NogsMPLS** [istarkov/babel-plugin-webpack-loaders#5]
I was trying to use this on my project and I kept getting stuff like:

```ERROR in ./components/button/Button.jsx
Module build failed: TypeError: C:/[some directory paths]/components/button/Button.jsx: invalid data```

I thought perhaps it was just the complexities of my app, so I decided to clone down this repo and run ```npm run example-build```, and I get the same error:

```TypeError: examples/myCoolLibrary/myCoolLibrary.js: invalid data```

Here is a screenshot:
![typerror](https://cloud.githubusercontent.com/assets/6899011/12210434/8962f764-b61f-11e5-95f6-f5a3a8b270e7.PNG)

I am on a Windows 7 machine, if that makes any difference. I'm not quite sure where to start on this, but I'll keep digging to see if I can find a solution/submit a PR. If you have any insight/advice that might be helpful, would be appreciated.

**Comment by istarkov** [comment]
It's never been tested on Windows, this is not operation system I use in my everyday life. So sorry, but I have zero ideas why and what is not running on windows of any version.

**Comment by NogsMPLS** [comment]
okay, I'll keep digging and see what I find, hopefully can figure it out and submit a PR to fix.

**Comment by istarkov** [comment]
Thank you!

**Comment by NogsMPLS** [comment]
oh, i do have one question for you. what version of node is supported? I'm assuming 4+?

**Comment by istarkov** [comment]
As here https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/.travis.yml
last stable, but it works for me on 4+

**Comment by NogsMPLS** [comment]
cool, thanks

**Comment by nkbt** [comment]
I guess I'm going to fix it anyway since I do support both win and
osx/linux in my libs and got win build failing this week.

**Comment by istarkov** [comment]
Looks like somewhere must be guide - how to prepare npm libraries for windows.

**Comment by nkbt** [comment]
That is actually quite simple :)

**Comment by NogsMPLS** [comment]
from what i can tell it's got something to do with line 17 in ```src/runWebPackSync.js```

basically once it his execFileSync, it just breaks. First thing I'd assume is windows pathing issues because that line has 4 paths inside it.

I know things like ```child_process.spawn()``` has a lot of issues on windows as well due to pathing, wouldn't be surprised if execFileSync suffers the same problem.

**Comment by nkbt** [comment]
There is an alternative crossplatform spawn `cross-spawn-async`.
Also all paths should be resolved with `path.resolve` or `path.join`.
That is pretty much it. Will have a look later today, no worries.

**Comment by istarkov** [comment]
This may help https://github.com/istarkov/babel-plugin-webpack-loaders/commit/c44d8e1d3df49c16fc2d0d44f27a13f20971db59

**Comment by nkbt** [comment]
@istarkov nah, still fails =(

```sh

> react-component-template@1.0.0 test C:\projects\react-component-template
> cross-env NODE_ENV=test babel-node test
 
C:\projects\react-component-template\node_modules\babel-core\lib\transformation\file\index.js:548
      throw err;
      ^
 
TypeError: C:/projects/react-component-template/src/example/App.js: invalid data
    at Socket.write (net.js:618:11)
    at Object.execFileSync (child_process.js:483:20)
    at exports.default (C:\projects\react-component-template\node_modules\babel-plugin-webpack-loaders\lib\runWebPackSync.js:37:48)
    at PluginPass.CallExpression (C:\projects\react-component-template\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:59:60)
    at newFn (C:\projects\react-component-template\node_modules\babel-traverse\lib\visitors.js:276:19)
    at NodePath._call (C:\projects\react-component-template\node_modules\babel-traverse\lib\path\context.js:74:18)
    at NodePath.call (C:\projects\react-component-template\node_modules\babel-traverse\lib\path\context.js:46:17)
    at NodePath.visit (C:\projects\react-component-template\node_modules\babel-traverse\lib\path\context.js:104:12)
    at TraversalContext.visitQueue (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:153:16)
    at TraversalContext.visitSingle (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:113:19)
    at TraversalContext.visit (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:197:19)
    at Function.traverse.node (C:\projects\react-component-template\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\projects\react-component-template\node_modules\babel-traverse\lib\path\context.js:114:22)
    at TraversalContext.visitQueue (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:153:16)
    at TraversalContext.visitMultiple (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:108:17)
    at TraversalContext.visit (C:\projects\react-component-template\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\projects\react-component-template\node_modules\babel-traverse\lib\index.js:139:17)
npm ERR! Test failed.  See above for more details.
Command exited with code 1
```
From https://ci.appveyor.com/project/nkbt/react-component-template/build/196

**Comment by NogsMPLS** [comment]
Oddly enough, I can run this from npm scripts:

```javascript
"build-sass": "webpack c:\\dev\\babel-plugin-webpack-loaders\\examples\\myCoolLibrary\\myCoolStyle.sass c:\\dev\\babel-plugin-webpack-loaders\\build\\myCoolLibrary\\assets\\.webpack.res.1452367566773_332155.js --config ./examples_webpack_configs/lib.webpack.config.js --colors --bail",
```
Which is just a straight rip of paths that I got from ```console.log()```-ing the path variables (plus some manual escaping of ```\```). That works totally fine, which, theoretically is what 
```javascript
const webPackStdOut = require('child_process')
    .execFileSync(webPackPath, [path, outPath, '--config', configPath, '--colors', '--bail']);
``` 
should be doing anyways. Feels like a Nodejs issue, and maybe we'll need to maybe find a way to circumvent having to use ```child_process.execFileSync()``` directly?

I'll keep looking into this.

**Comment by istarkov** [comment]
May be switching from execFileSync to execSync will help like here
https://github.com/Availity/availity-cli/issues/7

commit:
https://github.com/Availity/availity-cli/commit/f5dd3a48b5c5195ffbf1c1a097a5994c2b2a311d

**Comment by NogsMPLS** [comment]
hmmm, good idea, this works as intended, i *think*:

```javascript
  const webPackStdOut = require('child_process')
    .execSync('webpack' + ' ' + path + ' ' + outPath + ' --config' + ' ' + configPath + ' --colors' + ' --bail');
```
but note how I had to use 'webpack' as a string. Not sure if that is ideal. I have to go, but I'll check it out more tonight/tomorrow.

**Comment by istarkov** [comment]
It's better to use something like https://github.com/substack/node-shell-quote
because with `execSync` you need to prepare command line arguments (quotes, $ etc)
So the command with package above will likely be `execSync(quote([blabla]))`.

**Comment by istarkov** [comment]
Please checkout this PR https://github.com/istarkov/babel-plugin-webpack-loaders/pull/6
And test on windows, if it works I'll merge it.

Also if not adding node as first quote argument can help

```javascript
  const webPackStdOut = execSync(
    quote([
      'node',
      webPackPath,
      path, outPath,
      '--config', configPath,
      '--colors', '--bail',
    ])
  );
```

**Comment by NogsMPLS** [comment]
On windows I need to use the ```'node'``` string as you suggested.

OR, this works also:
```diff
 const webPackStdOut = execSync(
    quote([
-       webPackPath
+       'webpack',
        path, outPath,
        '--config', configPath,
        '--colors', '--bail',
        ])
    );
```
Whichever you prefer.

**Comment by istarkov** [comment]
In `npm`, I've added `node` because `webpack` may be not in `$PATH`

**Comment by NogsMPLS** [comment]
makes sense, thanks for looking into this!

**Comment by istarkov** [comment]
Thank for you guys, 
Windows patch will never come true without you (_lyrics song ;-)_)

@nkbt Can you confirm that last version works for you?

**Comment by nkbt** [comment]
@istarkov I briefly checked today on win machine and that fails the same way

```sh
C:\www\react-component-template {git}                                                                                          
{lamb} npm run test                                                                                                            
                                                                                                                               
> react-component-template@1.0.0 test C:\www\react-component-template                                                          
> cross-env NODE_ENV=test babel-node test                                                                                      
                                                                                                                               
                                                                                                                               
TypeError: C:/www/react-component-template/src/example/App.js: undefined is not a function                                     
    at exports.default (C:\www\react-component-template\node_modules\babel-plugin-webpack-loaders\lib\runWebPackSync.js:41:51) 
    at PluginPass.CallExpression (C:\www\react-component-template\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:59:60
    at newFn (C:\www\react-component-template\node_modules\babel-traverse\lib\visitors.js:276:19)                              
    at NodePath._call (C:\www\react-component-template\node_modules\babel-traverse\lib\path\context.js:74:18)                  
    at NodePath.call (C:\www\react-component-template\node_modules\babel-traverse\lib\path\context.js:46:17)                   
    at NodePath.visit (C:\www\react-component-template\node_modules\babel-traverse\lib\path\context.js:104:12)                 
    at TraversalContext.visitQueue (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:153:16)         
    at TraversalContext.visitSingle (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:113:19)        
    at TraversalContext.visit (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:197:19)              
    at Function.traverse.node (C:\www\react-component-template\node_modules\babel-traverse\lib\index.js:139:17)                
    at NodePath.visit (C:\www\react-component-template\node_modules\babel-traverse\lib\path\context.js:114:22)                 
    at TraversalContext.visitQueue (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:153:16)         
    at TraversalContext.visitMultiple (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:108:17)      
    at TraversalContext.visit (C:\www\react-component-template\node_modules\babel-traverse\lib\context.js:195:19)              
    at Function.traverse.node (C:\www\react-component-template\node_modules\babel-traverse\lib\index.js:139:17)                
    at NodePath.visit (C:\www\react-component-template\node_modules\babel-traverse\lib\path\context.js:114:22)                 
                                                                                                                               
npm ERR! Windows_NT 6.2.9200                                                                                                   
```


`undefined is not a function` is so awesome :trollface:

**Comment by istarkov** [comment]
`Undefined is not a function` is better than `Invalid data` ;-)

**Comment by NogsMPLS** [comment]
hmm...well, it's working *better* for me in my app, though I've still got some issues.

It's actually creating and moving files during build now and is past the TypeError: invalid data stage.

Now I've got some issues with string undefined when trying to run my app after build, but I think that maybe should be a different issue/ticket.

**Comment by istarkov** [comment]
Does current projects tests work? (npm run test)

**Comment by NogsMPLS** [comment]
I had to change the hashes in the runtime.spec.js file, but yeah, once I did that everything passed.

**Comment by istarkov** [comment]
It's fun but google and github know nothing about `invalid data stage` error :-)

**Comment by nkbt** [comment]
> Does current projects tests work? (npm run test)

Oh yeah, sure thing =). On both OSX and CircleCI. There is some problem with calling `exec`. 

By the way, I need to double-check if it is failing because of using `cross-env` which also calls its own `spawn`. Could be the case of some process args being swallowed.

**Comment by NogsMPLS** [comment]
Hmm...works for me for my app now and I'm using cross-env. I'll be interested to see what you find nkbt

Also, small note: while I got this plugin to work for me, it ended up making my build time go from like 30 seconds to over 3 minutes. That's mainly because of the webpack executions running in sync.

So what I ended up actually doing was taking https://github.com/michalkvasnicak/babel-plugin-css-modules-transform ripping it out into a tools folder which I reference in my babelrc and modified the script to add some PostCSS functionality:
```diff
+ import cssnext from 'postcss-cssnext';
+ import postcssImport from 'postcss-import';
//stuff
- require('css-modules-require-hook')({ ...defaultOptions, ...opts })
+ require('css-modules-require-hook')({ ...defaultOptions, ...opts, prepend: [postcssImport(), cssnext() ]});
```
Since I'm only using PostCSS and not SASS or other things I realized I don't need the full power of webpack for my solution.

Still think this repo is good though, and I'll be following along as it gets improved!

**Comment by nkbt** [comment]
https://ci.appveyor.com/project/nkbt/react-component-template/build/199 works for me now :fire:   babel-plugin-webpack-loaders@0.1.2

**Comment by istarkov** [comment]
Looks like I start use https://www.appveyor.com/ too.
Thank you for your help @nkbt, I close this issue.

**Comment by nkbt** [comment]
Thanks for the fix. All's green now =)
