### ISSUE TITLE
Generated Module not found

### ISSUE THREAD

**Issue by MoOx** [istarkov/babel-plugin-webpack-loaders#51]
Hi,

I am trying to use babel-register instead of defining the config in the babelrc

So I run babel-register like this

```
#!/usr/bin/env node

// babel register, yeah
require("babel-register")({
  "env": {
    "statinamic": {
      "plugins": [
        [
          "babel-plugin-webpack-loaders",
          {
            "config": require("path").join(
              __dirname, "webpack.config.babel.js"
            ),
            "verbose": true,
          },
        ],
      ],
    },
  },
})

require(process.argv[2]) // my script to run
```

I have a server (the script called with argv[2]) that run a dev server that
- use webpack middleware, to build webpack for client
- prerender the same code for development purpose (=> a isomorphic dev server).

The server start, the client code is correctly built, but when my prenrender start his job, I got a weird error like the generated file per your plugin was missing (the dist/.webpack.res.*).

```
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js in /Users/MoOx/Sync/Development/statinamic/docs
    at /Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:726:13
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:52:16
    at done (/Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:241:17)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:44:16
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:723:17
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:167:37
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Users/MoOx/Sync/Development/statinamic/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
resolve file
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js.js doesn't exist
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js.json doesn't exist
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js doesn't exist
resolve directory
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js doesn't exist (directory default file)
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js/package.json doesn't exist (directory description file)
Error: /Users/MoOx/Sync/Development/statinamic/docs/web_modules/layouts/Page/index.js: Command failed: node /Users/MoOx/Sync/Development/statinamic/node_modules/webpack/bin/webpack.js /Users/MoOx/Sync/Development/statinamic/docs/web_modules/layouts/Page/index.css /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js --config /Users/MoOx/Sync/Development/statinamic/src/bin/webpack.config.babel.js --colors --bail
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js in /Users/MoOx/Sync/Development/statinamic/docs
    at /Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:726:13
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:52:16
    at done (/Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:241:17)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:44:16
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:723:17
    at /Users/MoOx/Sync/Development/statinamic/node_modules/async/lib/async.js:167:37
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/MoOx/Sync/Development/statinamic/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/MoOx/Sync/Development/statinamic/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Users/MoOx/Sync/Development/statinamic/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
resolve file
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js.js doesn't exist
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js.json doesn't exist
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js doesn't exist
resolve directory
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js doesn't exist (directory default file)
  /Users/MoOx/Sync/Development/statinamic/docs/dist/.webpack.res.1457337445196_826582.js/package.json doesn't exist (directory description file)

    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at exports.default (/Users/MoOx/Sync/Development/statinamic/docs/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:41:51)
    at PluginPass.CallExpression (/Users/MoOx/Sync/Development/statinamic/docs/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:86:60)
    at newFn (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/path/context.js:75:18)
    at NodePath.call (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/Users/MoOx/Sync/Development/statinamic/node_modules/babel-traverse/lib/index.js:141:17)
```

Any idea?

**Comment by MoOx** [comment]
The culpirit: webpack.config/output.filename. This option should not be set (I merged 2 things and missed that).
Maybe you should warn or throw if this key exist? (Or warn + ignore it).

**Comment by istarkov** [comment]
Is it for babel-register only or for any configuration?
(Will look few days later)

**Comment by MoOx** [comment]
Any :)
