### ISSUE TITLE
Cannot resolve .webpack.res.1462025829429_520036.js

### ISSUE THREAD

**Issue by giacomorebonato** [istarkov/babel-plugin-webpack-loaders#71]
Hi, I am trying to using this loader to test a ReactJS application with Ava test runner.
Probably I am doing something wrong with the configuration, but I can't understand.  
This is how I launch Ava 
```CONFIG=$(pwd)/webpack.config.js BABEL_DISABLE_CACHE=1 NODE_ENV=test ava```.  

And this is my .babelrc
```
{
  "plugins": ["lodash"],
  "presets": ["es2015", "react"],
  "env": {
    "test": {
      "plugins": [
        [
          "babel-plugin-webpack-loaders",
          {
            "config": "${CONFIG}",
            "verbose": false,
          }
        ]
      ]
    }
  }
}
```

This is the test I am trying to execute  
```
import React from 'react'
import { shallow } from 'enzyme'
import '../setup'
import test from 'ava'
import Sidebar from './Sidebar'
import Content from './Content'
import Front from './Front'

test('<Front /> root component', (t) => {
  const wrapper = shallow(<Front />)

  t.is(wrapper.find(Sidebar).length, 1)
  t.is(wrapper.find(Content).length, 1)
})
```

What are these .webpack.res files that it is not finding?
```
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' public/test/.webpack.res.1462025829429_520036.js in client/front
    at node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at node_modules/async/lib/async.js:726:13
    at node_modules/async/lib/async.js:52:16
    at done (node_modules/async/lib/async.js:241:17)
    at node_modules/async/lib/async.js:44:16
    at node_modules/async/lib/async.js:723:17
    at node_modules/async/lib/async.js:167:37
    at node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
resolve file
  public/test/.webpack.res.1462025829429_520036.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.webpack.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.web.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.json doesn't exist
resolve directory
  public/test/.webpack.res.1462025829429_520036.js doesn't exist (directory default file)
  public/test/.webpack.res.1462025829429_520036.js/package.json doesn't exist (directory description file)
node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

Error: client/front/Sidebar/Sidebar.js: Command failed: node node_modules/webpack/bin/webpack.js client/front/Sidebar/sidebar.css public/test/.webpack.res.1462025829429_520036.js --config webpack.config.js --bail
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' public/test/.webpack.res.1462025829429_520036.js in client/front
    at node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at node_modules/async/lib/async.js:726:13
    at node_modules/async/lib/async.js:52:16
    at done (node_modules/async/lib/async.js:241:17)
    at node_modules/async/lib/async.js:44:16
    at node_modules/async/lib/async.js:723:17
    at node_modules/async/lib/async.js:167:37
    at node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
resolve file
  public/test/.webpack.res.1462025829429_520036.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.webpack.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.web.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.js doesn't exist
  public/test/.webpack.res.1462025829429_520036.js.json doesn't exist
resolve directory
  public/test/.webpack.res.1462025829429_520036.js doesn't exist (directory default file)
  public/test/.webpack.res.1462025829429_520036.js/package.json doesn't exist (directory description file)

    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at exports.default (node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:41:51)
    at PluginPass.CallExpression (node_modules/babel-plugin-webpack-loaders/lib/plugin.js:89:60)
    at newFn (node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:135:17)
    at Object.traverse [as default] (node_modules/babel-traverse/lib/index.js:69:12)
    at node_modules/babel-core/lib/transformation/file/index.js:513:33
    at Array.forEach (native)
    at File.transform (node_modules/babel-core/lib/transformation/file/index.js:510:23)
    at node_modules/babel-core/lib/transformation/pipeline.js:49:19
    at File.wrap (node_modules/babel-core/lib/transformation/file/index.js:528:16)
    at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:17)
    at Object.transformFileSync (node_modules/babel-core/lib/api/node.js:124:10)
    at compile (node_modules/babel-register/lib/node.js:98:20)
    at loader (node_modules/babel-register/lib/node.js:126:14)
    at require.extensions.(anonymous function) (node_modules/babel-register/lib/node.js:136:7)
    at extensions.(anonymous function) (node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (client/front/Sidebar/index.js:6:19)
    at Module._compile (module.js:413:34)
    at loader (node_modules/babel-register/lib/node.js:126:5)
    at require.extensions.(anonymous function) (node_modules/babel-register/lib/node.js:136:7)
    at extensions.(anonymous function) (node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (client/front/Front.test.js:5:1)
    at Module._compile (module.js:413:34)
    at extensions.(anonymous function) (node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (node_modules/ava/lib/test-worker.js:93:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
# client/front/Front.test.js exited with a non-zero exit code: 1
not ok 1 - client/front/Front.test.js exited with a non-zero exit code: 1
```

**Comment by istarkov** [comment]
OS, node version, npm version? 

IMHO the problem is here https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/runWebPackSync.js#L14
Your config output path does not exists or relative to some different folder. Be sure to set full path not relative, as ava is different about process directory etc.

**Comment by giacomorebonato** [comment]
Node v5.10.0
NPM 3.8.3

This is my output in webpack
```
  output: {
    path: path.join(__dirname, '/public/' + NODE_ENV),
    filename: '[name].js',
    libraryTarget: 'commonjs2'
  }
```

Thank you for the advice. I will try something.

**Comment by giacomorebonato** [comment]
A little bit better removing the output section
```
/Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

TypeError: /Users/grebonato/Code/sdk_showcase/client/front/Sidebar/Sidebar.js: Cannot read property 'path' of undefined
    at exports.default (/Users/grebonato/Code/sdk_showcase/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:37:46)
    at PluginPass.CallExpression (/Users/grebonato/Code/sdk_showcase/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:89:60)
    at newFn (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/index.js:135:17)
    at Object.traverse [as default] (/Users/grebonato/Code/sdk_showcase/node_modules/babel-traverse/lib/index.js:69:12)
    at /Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/file/index.js:513:33
    at Array.forEach (native)
    at File.transform (/Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/file/index.js:510:23)
    at /Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/pipeline.js:49:19
    at File.wrap (/Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/file/index.js:528:16)
    at Pipeline.transform (/Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/transformation/pipeline.js:46:17)
    at Object.transformFileSync (/Users/grebonato/Code/sdk_showcase/node_modules/babel-core/lib/api/node.js:124:10)
    at compile (/Users/grebonato/Code/sdk_showcase/node_modules/babel-register/lib/node.js:98:20)
    at loader (/Users/grebonato/Code/sdk_showcase/node_modules/babel-register/lib/node.js:126:14)
    at require.extensions.(anonymous function) (/Users/grebonato/Code/sdk_showcase/node_modules/babel-register/lib/node.js:136:7)
    at extensions.(anonymous function) (/Users/grebonato/Code/sdk_showcase/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/grebonato/Code/sdk_showcase/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/grebonato/Code/sdk_showcase/client/front/Sidebar/index.js:6:19)
    at Module._compile (module.js:413:34)
    at loader (/Users/grebonato/Code/sdk_showcase/node_modules/babel-register/lib/node.js:126:5)
    at require.extensions.(anonymous function) (/Users/grebonato/Code/sdk_showcase/node_modules/babel-register/lib/node.js:136:7)
    at extensions.(anonymous function) (/Users/grebonato/Code/sdk_showcase/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/grebonato/Code/sdk_showcase/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/grebonato/Code/sdk_showcase/client/front/Front.test.js:5:1)
    at Module._compile (module.js:413:34)
    at extensions.(anonymous function) (/Users/grebonato/Code/sdk_showcase/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/grebonato/Code/sdk_showcase/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/grebonato/Code/sdk_showcase/node_modules/ava/lib/test-worker.js:93:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
# client/front/Front.test.js exited with a non-zero exit code: 1
```

**Comment by istarkov** [comment]
I don't know ;-)
 
Current project has a working ava test, you could check anything just taking current config etc, and then downgrade to your Error.

There are a lot of different options which can cause any errors ;-)

**Comment by giacomorebonato** [comment]
I will keep the issue open just for a little bit, in case I find the issue. Cheers.

**Comment by istarkov** [comment]
IMHO it's my bug here https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/runWebPackSync.js#L14
``` join(config.output.path)``` I need to check that output exists ;-)

**Comment by istarkov** [comment]
As a temp workaround just don't delete output in config. I can't fix it now.

**Comment by giacomorebonato** [comment]
I took the webpack command that execSync is executing and tried to run it into the terminal, but (obviously) I get the same error.
The outpath provided to webpack command really exists... but the problem is there

**Comment by istarkov** [comment]
If you run webpack alone without this lib and problem is exists, so the problem is not in this library.
May be you forget to set up ava with babel https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/package.json#L75-L85 or something else.

**Comment by iansinnott** [comment]
I also ran into this exact error when using Webpack 2. I think the issue might have been that the generated webpack command was slightly off. Updating the command to use more explicit command line options seemed to work for me:

```js
  var outPath = config.output && config.output.path || DEFAULT_OUTPUT_PATH;
  var outFilename = '.webpack.res.' + rnd + '.js';
  var outFilepath = path.join(outPath, outFilename);

  var command = [
    'node', // for windows support
    webPackPath,
    '--config', configPath,
    '--entry', path,
    '--output-path', outPath,
    '--output-filename', outFilename,
    '--bail'
  ].join(' ')
```

Hope that helps anyone still having this issue.

However, I did not submit a PR for this because I ended up running into other react/webpack/flow issues and finally decided to just use Jest as @istarkov recommends on the front page. I really like Ava but it was simply taking way to much energy to get everything setup to run properly together.
