### ISSUE TITLE
Plugin hangs without errors, seemly does nothing

### ISSUE THREAD

**Issue by sortsen** [istarkov/babel-plugin-webpack-loaders#85]
Afaics I did everything required to use this plugin. However when I do npm run start, it display the text below and seemingly does nothing. It never stops and no errors appear.

```
babel-plugin-webpack-loader:
js and jsx files in loaders is unsupported by webpack-loader plugin.
all babel settings in loader will be skipped
```

Even when I set verbose to true in babel.rc, it gives me nothing.

**Comment by istarkov** [comment]
When I run one of my program, it hangs, could you resolve my issue having such information? 
BTW this library contains tests, examples etc, it could help.

**Comment by tleunen** [comment]
I have the same issue. It doesn't seem to do nothing.
I can't say much information neither except that I'm using the module resolver of webpack. Have setup it like this:
```
resolve: {
        root: path.join(__dirname, 'src'),
        modules: [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, 'src')
        ]
    },
```
So the root works in my browser, and the modules should be used by this plugin.

After stopping the execution, I get an error:
```
~/d/a/projectA ❯ ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tleunen/dev/projectA/dist/.webpack.res.1463437810440_752336.js in /Users/tleunen/dev/projectA
    at /Users/tleunen/dev/projectA/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/tleunen/dev/projectA/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/tleunen/dev/projectA/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/tleunen/dev/projectA/node_modules/async/lib/async.js:726:13
    at /Users/tleunen/dev/projectA/node_modules/async/lib/async.js:52:16
    at done (/Users/tleunen/dev/projectA/node_modules/async/lib/async.js:241:17)
    at /Users/tleunen/dev/projectA/node_modules/async/lib/async.js:44:16
    at /Users/tleunen/dev/projectA/node_modules/async/lib/async.js:723:17
    at //Users/tleunen/dev/projectA/node_modules/babel-core/lib/transformation/file/index.js:614
      throw err;
      ^

Error: /Users/tleunen/dev/projectA/src/components/navigation/MyComponent.js: ENOENT: no such file or directory, open '/Users/tleunen/dev/projectA/dist/.webpack.res.1463437810440_752336.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at fs.readFileSync (fs.js:502:33)
    at exports.default (/Users/tleunen/dev/projectA/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:50:44)
    at PluginPass.CallExpression (/Users/tleunen/dev/projectA/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:89:60)
    at newFn (/Users/tleunen/dev/projectA/node_modules/babel-traverse/lib/visitors.js:310:19)
    at NodePath._call (/Users/tleunen/dev/projectA/node_modules/babel-traverse/lib/path/context.js:78:18)
``` 

Hopefully it can helps a bit @istarkov :s

**Comment by tleunen** [comment]
Looks like this is causing some issues https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/runWebPackSync.js#L18-L26

**Comment by joefiorini** [comment]
I've spent a few hours trying to dig into this. I think I finally managed to get to the bottom of it.

I've isolated 2 issues: having an entry point and an output filename specified in the webpack config. You can see my webpack config here https://gist.github.com/joefiorini/5c41af94cff318a353994c582d2b2c9c#file-webpack-config-babel-js. The commented out lines are the ones I had to remove to make it work.

The first issue is the cause of the hanging. I think it's because I'm using babel-loader, which is trying to run through the plugin and possibly loading the plugin and webpack config again. Removing the entry point fixes this (removing babel-loader just results in a syntax error from webpack).

The other issue is (maybe unrelated to the hanging?) that when I specify an output filename in my config webpack reports that it can't find the module/filename `.webpack.res.${...snip}.js`. Once again guessing here, but maybe webpack tries to create the output filename before writing to it, and on create the config takes precedence but on the write the CLI wins. Can anyone confirm this?

To reproduce these issues, you should be able to [clone this gist](https://gist.github.com/joefiorini/5c41af94cff318a353994c582d2b2c9c) and run `node run.js` (may need to install some dependencies, sorry don't have time atm to create a separate package.json).
