### ISSUE TITLE
CSS modules compose from other file fails

### ISSUE THREAD

**Issue by kavsingh** [istarkov/babel-plugin-webpack-loaders#97]
Hello again!

Was having trouble getting ava tests working when composing css modules between files. Tried modifying some of the provided examples to investigate.

Modified `test/assets/withoutExtractText/style.css` to the following (having added the referenced file and style to the folder):
```css

.main {
  composes: othermain from 'postcss!./otherstyle.css';
  width: 100%;
}

.item {
  height: 100%;
}

```

and got this error when running `npm run ava-test`:
```
babel-plugin-webpack-loaders (master) ✗ npm run ava-test

> babel-plugin-webpack-loaders@0.5.0 ava-test /Users/kav/lib/babel-plugin-webpack-loaders
> CONFIG=$(pwd)/test/runtime.webpack.config.babel.js BABEL_DISABLE_CACHE=1 NODE_ENV=AVA_TEST ava


/Users/kav/lib/babel-plugin-webpack-loaders/test/ava/index.js:10
  "main": "style__main " + __webpack_require__(0).locals["othermain"] + "",
                           ^

ReferenceError: __webpack_require__ is not defined
    at Object.<anonymous> (/Users/kav/lib/babel-plugin-webpack-loaders/test/ava/index.js:2:1)
    at Module._compile (module.js:541:32)
    at extensions.(anonymous function) (/Users/kav/lib/babel-plugin-webpack-loaders/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kav/lib/babel-plugin-webpack-loaders/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kav/lib/babel-plugin-webpack-loaders/node_modules/ava/lib/test-worker.js:93:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
  ✖ test/ava/index.js exited with a non-zero exit code: 1

  0 tests passed
  1 uncaught exception


npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/kav/.nvm/versions/node/v6.2.0/bin/node" "/Users/kav/.nvm/versions/node/v6.2.0/bin/npm" "run" "ava-test"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! babel-plugin-webpack-loaders@0.5.0 ava-test: `CONFIG=$(pwd)/test/runtime.webpack.config.babel.js BABEL_DISABLE_CACHE=1 NODE_ENV=AVA_TEST ava`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-plugin-webpack-loaders@0.5.0 ava-test script 'CONFIG=$(pwd)/test/runtime.webpack.config.babel.js BABEL_DISABLE_CACHE=1 NODE_ENV=AVA_TEST ava'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-plugin-webpack-loaders package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     CONFIG=$(pwd)/test/runtime.webpack.config.babel.js BABEL_DISABLE_CACHE=1 NODE_ENV=AVA_TEST ava
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-plugin-webpack-loaders
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-plugin-webpack-loaders
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kav/lib/babel-plugin-webpack-loaders/npm-debug.log
```

same thing happens if use
```css

.main {
  composes: othermain from './otherstyle.css';
  width: 100%;
}
```

Thanks!

**Comment by istarkov** [comment]
Will look, not sure that this problem can be solved if `css-modules` generated code contains `require` and other dynamic stuff in such case.

BTW I don't use css-modules `composes` from other files, 
as it can cause undefined order of css classes https://github.com/css-modules/css-modules/issues/12

I prefer to use preprocessor like sass and use `@import` directive.

**Comment by kavsingh** [comment]
Thanks for the insight about the compose rules, will investigate that

**Comment by GabeMedrash** [comment]
I ran into this exact issue. My immediate need is to run a node-based unit test and I'm generally less interested for now in testing the application of styles than I am in other functionality, so I found that I could entirely side-step this by chaining [block-loader](https://www.npmjs.com/package/block-loader) before `css-loader`, and using it to just remove the offending `composes` directive.

In case you're interested, here's my webpack config for my test runner:
```
var webpack = require('webpack');

module.exports = {
  output: {
    libraryTarget: 'commonjs2',
    path: __dirname
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        exclude: /node_modules/,
        loader: [
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          'postcss-loader',
          __dirname + '/strip-compose-loader'
        ].join('!')
      },
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  }
};
```

And here are the contents of the file that `__dirname + '/strip-compose-loader'` resolves to:
```
var blockLoader = require('block-loader');
var options = {
  start: 'composes',
  end: '\n',
  process: function () {
    return '';
  }
};

module.exports = blockLoader(options);
```

**Comment by istarkov** [comment]
Thank you, so good idea!

**Comment by kavsingh** [comment]
Thanks @GabeMedrash, that's great! And thanks @istarkov for the awesome plugin.

**Comment by SpencerCDixon** [comment]
So removing the 'composes' with @GabeMedrash suggestion totally fixes the first issue.  My second problem I'm running into is I use `@value primary_color: red` type syntax with css modules and it now borks on that I believe.  Anyone have any insights?

**Comment by tsnieman** [comment]
Dunno why, but I couldn't get `block-loader` working like @GabeMedrash suggested. To remedy this, I just made my own loader that is for specifically removing 'composes' lines. Here it is in case anyone else was having issues:

```js
// Custom webpack loader which simply removes any use of 'composes'.
// This is because this bug https://github.com/istarkov/babel-plugin-webpack-loaders/issues/97
// causing issues with testing.
module.exports = function removeComposes(source) {
  if (process.env.NODE_ENV === 'test') {
    const hasComposes = source.indexOf('composes') > 0;
    if (!hasComposes) return source;

    var numOfOccurences = source.match(/composes/g).length;

    var modifiedSource = source;
    for (var i = 0; i < numOfOccurences; i++) {
      var startIndex = modifiedSource.indexOf('composes');
      var endIndex = modifiedSource.indexOf('\n', startIndex);
      var removableLength = (endIndex - startIndex);
      var toRemove = modifiedSource.substr(startIndex, removableLength);
      modifiedSource = modifiedSource.replace(toRemove, '');
    }

    return modifiedSource;
  }

  return source;
};
```
also available @ https://gist.github.com/tsnieman/c3028380653983de3f5d925e73944808

@SpencerCDixon You could probably modify this pretty easily to remove `@value` stuff.

**Comment by SpencerCDixon** [comment]
Nice, appreciate it, thanks!

**Comment by cfatorNSS** [comment]
We are also running into issues with the compose: [style name] [path to css file] feature.  What we've noticed is that the style name applied to the DOM element for the compose is slightly off.  In our case its rendered as "base__TBBorderContainer--3rM32", but if we change that to "styles__TBBorderContainer--3rM32" we can see the composed styles render correctly.  

I'm just picking up webpack and have a feeling that there is a configuration in there that needs adjusting for this.

**Comment by neelendu25** [comment]
One simple way is to import 'ignore-styles'; in your test classes..
